version = 0.1

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "production-todo-list-aws"
s3_prefix = "todo-list-aws"
region = "us-east-1"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback = false
parameter_overrides = "Stage=\"production\""
image_repositories = []
